services:
  postgres-db:
    container_name: postgres-go # Este es el host
    image: postgres:17.5-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
      # - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

volumes:
  postgres-db:
# Este volumen es interno al proyecto, y si no existe, créalo automáticamente.
